### ISSUE TITLE
Get more info about the design

### ISSUE THREAD

**Issue by danielnydrle** [danielnydrle/FreeForYou#10]

**Comment by danielnydrle** [comment]
- [ ] Logo v záhlaví není čitelný, zeptat se na možný řešení (obr. 1)
- [ ] Mají být loga klientů klikací odkazy? (obr. 2)
- [ ] Přepisy energií - ikonka bude stejná, nebo budou 3 různý jako doposud? (obr. 3)
- [ ] Jak to bude s tim iframem místo formuláře? (obr. 4)

obr. 1
![image](https://user-images.githubusercontent.com/57211233/132916657-9d325706-8a42-4953-b1c0-23e04b15ae26.png)

obr. 2
![image](https://user-images.githubusercontent.com/57211233/132916916-4fe245bd-beef-4641-93af-4ce8a0de34c6.png)

obr. 3
![image](https://user-images.githubusercontent.com/57211233/132916954-12497817-787e-4224-81df-8ab671be3892.png)

obr. 4
![image](https://user-images.githubusercontent.com/57211233/132916974-89e5af05-bc1e-42a2-b73b-18441e7120e0.png)

**Comment by pavelmedia** [comment]
1) logo: 
Dovolil jsem si upravit. Posílám v příloze s bílým textem. PNG i SVG 

2) ikony: 
Nebudou stejné, máš pravdu :) Je to chyba. Při importu PSD si Adobe XD neporadilo s těmito vektory a špatně je zobrazilo. 
Platí původní. Pro případ také v příloze. 

3) Mapa: 
Souhlasím ;) = mapa bude staticky img s proklikem:
Link: https://mapy.cz/s/detenegevu 
Náhled v příloze. 

[rere8webfreeforyoupodklady.zip](https://github.com/danielnydrle/FreeForYou/files/7148576/rere8webfreeforyoupodklady.zip)
