### ISSUE TITLE
Feedback Round 2

### ISSUE THREAD

**Issue by pavelmedia** [danielnydrle/FreeForYou#26]
https://www.evernote.com/shard/s436/sh/cae20b0b-c259-8aab-bccc-ddb7601286a4/e29503314c2debf65fd067ee35cbb823

druha cast docu je puvodni feedback R1, to poznas

**Comment by danielnydrle** [comment]
@pavelmedia 
Zeptat se:

- [ ] Reference - podbarvení stejnou barvou (celý sekce, nebo jednotlivejch položek s lidma v carouselu)? Kdyby to byla celá sekce, tak to vypadá takhle, což je podle mě divný:
![image](https://user-images.githubusercontent.com/57211233/133493502-16374bb2-7095-470e-8ef6-e3c9113d58fb.png)

- [ ] Malý contrast ratio u následujících elementů (můžu ztmavit?):
![image](https://user-images.githubusercontent.com/57211233/133494326-c041bc76-4e60-4ee6-8b25-7b2151c31188.png)
![image](https://user-images.githubusercontent.com/57211233/133494407-95c85b71-5fe1-43e8-8813-16ef0778082c.png)
(všechno s touhle zelenou)

by mělo bejt takhle zatim všechno
